from PyQt5.QtCore import Qt


COL_BLACK = "#0A0A0A"
COL_DARK = "#141414"
COL_GRAY = "#2A2A2A"
COL_BG = COL_BLACK
COL_TEXT = "#E0E0E0"
COL_GREEN = "#00FF7F"
COL_GREEN_MID = "#00CC60"
COL_GREEN_DRK = "#2A2A2A"
COL_WHITE = "#FFFFFF"
COL_YELLOW = "#FFD700"
COL_RED = "#FF3333"
COL_TIMESTAMP = "#FF8C00"
COL_GRID_MINOR = "#1A2A1A"
COL_GRID_MAJOR = "#2A3A2A"
COL_WAVE_ORANGE = "#E06020"
COL_WAVE_RED = COL_RED
COL_BTN_ACTIVE_BG = "#1E4A7A"
COL_BTN_ACTIVE_TEXT = "#6AACF5"
COL_BEAT_S = "#FF9900"
COL_CROSSHAIR = "#00E5FF"

TOOL_SELECT = "select"
TOOL_RULER = "ruler"
TOOL_CALIPER = "caliper"
TOOL_MAGNIFY = "magnify"
TOOL_ANNOTATE = "annotate"

TOOL_CURSORS = {
    TOOL_SELECT: Qt.ArrowCursor,
    TOOL_RULER: Qt.CrossCursor,
    TOOL_CALIPER: Qt.SplitHCursor,
    TOOL_MAGNIFY: Qt.CrossCursor,
    TOOL_ANNOTATE: Qt.PointingHandCursor,
}

PAPER_SPEEDS = [12.5, 25.0, 50.0]
GAINS = [5, 10, 20]
MAGNIFIER_ZOOM_LEVELS = [2, 3, 4, 5, 6]
ADC_TO_MV = 1.0 / 200.0
